import{a as P,S as B,i as c}from"./assets/vendor-DcHCnVjq.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const E="55943354-aedacad3df1b2c8419ab26500",M="https://pixabay.com/api/",h=async(t,o)=>(await P.get(M,{params:{key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data;let u=null;const g=document.querySelector(".gallery"),l=document.querySelector(".loader"),d=document.querySelector(".load-more-btn");function y(t){const o=t.map(({webformatURL:i,largeImageURL:n,tags:e,likes:r,views:s,comments:v,downloads:q})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${n}">
            <img class="gallery-image" src="${i}" alt="${e}" />
          </a>
          <div class="info-container">
            <p class="info-item"><b>Likes</b> <br>${r}</p>
            <p class="info-item"><b>Views</b> <br>${s}</p>
            <p class="info-item"><b>Comments</b> <br>${v}</p>
            <p class="info-item"><b>Downloads</b> <br>${q}</p>
          </div>
        </li>
      `).join("");g.insertAdjacentHTML("beforeend",o),u?u.refresh():u=new B(".gallery a",{captionsData:"alt",captionDelay:250})}function $(){g.innerHTML=""}function b(){l&&l.classList.remove("is-hidden")}function L(){l&&l.classList.add("is-hidden")}function x(){d&&d.classList.remove("is-hidden")}function m(){d&&d.classList.add("is-hidden")}const p=document.querySelector(".form"),O=document.querySelector(".load-more-btn");let f="",a=1,w=0;p.addEventListener("submit",async t=>{t.preventDefault();const o=t.currentTarget.elements["search-text"].value.trim();if(o!==""){f=o,a=1,$(),m(),b();try{const i=await h(f,a);if(w=i.totalHits,i.hits.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(i.hits),S()}catch(i){console.error(i),c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L(),p.reset()}}});O.addEventListener("click",async()=>{a+=1,m(),b();try{const t=await h(f,a);y(t.hits),R(),S()}catch(t){console.error(t),c.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{L()}});function S(){const t=Math.ceil(w/15);a>=t?(m(),c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):x()}function R(){const t=document.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
